on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      # - '**'

env:
  CI_JOB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Cache layers
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-

      - name: Run Skaffold pipeline as command
        uses: hiberbee/github-action-skaffold@1.27.0
        id: build
        with:
          command: build --tag ${{ github.sha }}
          repository: ghcr.io/${{ github.repository_owner }}
  stage-deploy:
    name: Deploy on stage
    needs: converge
    runs-on: ubuntu-latest
    steps:
      - name: ConfigCreate
        run: |
          mkdir ~/.kube/
          echo "${{ secrets.KUBECONFIG }}" > config
          mv config ~/.kube/
          ls ~/.kube/
          kubectl set image deployment/link-shortener-stage  link-shortener=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA -n stage	
